name: Feature Branch Cleanup

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]] || ! [[ "${GITHUB_REF_NAME}" =~ ^[0-9]+-.* ]]; then
            echo "Feature branch deployment can not be initiated on branch '$GITHUB_REF_NAME'" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CDK_ROLE_ARN }}
          role-session-name: js-assertion-cheat-sheet-feature-branch-cleanup
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: cdk
        run: npm install

      - name: Set branch ID
        run: echo "BRANCH_ID=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Download CDK output
        uses: actions/download-artifact@v3
        with:
          name: cdk-output

      - name: Load CDK output
        run: |
          CDK_OUTPUT=$(cat ./cdk-output.json)
          echo "AWS_BUCKET_NAME=$(echo $CDK_OUTPUT | jq -r '.BucketName')" >> $GITHUB_ENV
          echo "AWS_DISTRIBUTION_ID=$(echo $CDK_OUTPUT | jq -r '.DistributionId')" >> $GITHUB_ENV

      - name: Remove from S3
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ env.AWS_BUCKET_NAME }}
          PATH_TO_DELETE: ${{ env.BRANCH_ID }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.AWS_DISTRIBUTION_ID }}
          PATHS: "/${{ env.BRANCH_ID }}/*"

      - name: Print cleanup result
        run: |
          echo "Branch '${{ env.BRANCH_ID }}' has been successfully removed from AWS" >> $GITHUB_STEP_SUMMARY
