name: Feature Branch Cleanup

on:
  delete:
    branches:
      - '[0-9]+-**'

permissions:
  id-token: write
  contents: read

jobs:
  cleanup:
    name: Clean up feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "BRANCH_ID=${{ github.event.ref#refs/heads/ }}" >> $GITHUB_ENV

      - name: Configure AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CLI_ROLE_ARN }}
          role-session-name: js-assertion-cheat-sheet-feature-branch-cleanup
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete branch folder from S3
        run: |
          aws s3 rm s3://${{ env.AWS_BUCKET_NAME }}/${{ env.BRANCH_ID }} --recursive

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.AWS_DISTRIBUTION_ID }}
          PATHS: "/${{ env.BRANCH_ID }}/*"

      - name: Deactivate deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: aws-development
          ref: ${{ env.BRANCH_ID }}
          onlyDeactivateDeployments: true
