name: Main Branch Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+-**' # FOR TESTING
    paths-ignore:
      - '**.drawio'
      - '**.md'
      - '**.png'
  pull_request:
    branches:
      - main
    types: [closed]

env:
  BRANCH_ID: main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build: # Incomplete, scope of https://github.com/orgs/Idea-Pool/projects/4/views/1?pane=issue&itemId=10153808
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Archive Build # This archives the build folder, for now its just an index.html
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build
          retention-days: 1
  deploy:
    environment:
      name: github-pages
    name: Deploy main branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Healthcheck # Scope of https://github.com/orgs/Idea-Pool/projects/4/views/1?pane=issue&itemId=56848307
        run: echo "healthcheck"
      - name: Print deployed URL
        run: |
          URL="https://${{ github.repository_owner }}.github.io/${{ github.repository }}/${{ env.BRANCH_ID }}"
          echo "Branch '${{ env.BRANCH_ID }}' has been successfully deployed: $URL" >> $GITHUB_STEP_SUMMARY
