name: Main Deployment
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "cdk/lib/**"
  #     - "cdk/bin/**"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == '6-set-up-main-branch-deployment' }}
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CDK_ROLE_ARN }}
          role-session-name: js-assertion-cheat-sheet-main-deployment
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install packages
        working-directory: cdk
        run: npm install
      - name: Deploy stack
        working-directory: cdk
        run: npm run deploy -- --require-approval never --outputs-file ./cdk-outputs.json
      - name: Set CDK output
        id: cdk_output
        run: | 
          CDK_OUTPUT=$(cat cdk/cdk-outputs.json)
          echo "CDK Output:" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo "$CDK_OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "BucketName=$(echo $CDK_OUTPUT | jq -r '.JSAssertionCheatSheet.BucketName')" >> $GITHUB_OUTPUT
          echo "DistributionId=$(echo $CDK_OUTPUT | jq -r '.JSAssertionCheatSheet.DistributionId')" >> $GITHUB_OUTPUT
          echo "WebsiteUrl=$(echo $CDK_OUTPUT | jq -r '.JSAssertionCheatSheet.WebsiteUrl')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
      - name: Set dynamic variables
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS_TOKEN }}
        run: |
          gh variable set AWS_BUCKET_NAME --body "${{ steps.cdk_output.outputs.BucketName }}" --env aws-development
          gh variable set AWS_DISTRIBUTION_ID --body "${{ steps.cdk_output.outputs.DistributionId }}" --env aws-development
          gh variable set AWS_WEBSITE_URL --body "${{ steps.cdk_output.outputs.WebsiteUrl }}" --env aws-development
      - name: Upload build artifact artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdk-output
          path: |
            cdk/cdk-outputs.json
