name: Main Branch Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.drawio'
      - '**.md'
      - '**.png'

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build: # Incomplete, scope of https://github.com/orgs/Idea-Pool/projects/4/views/1?pane=issue&itemId=10153808
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install
        run: npm ci
      - name: Build and test
        run: npm run build
        env:
          ASTRO_SITE: https://js-assertion.ideapool.community
          PUBLIC_VERSION: v0.1.0-${{ github.sha }}
      - name: Archive Build # This archives the build folder, for now its just an index.html
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist
          retention-days: 1
  deploy:
    environment:
      name: github-pages
    name: Deploy main branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Healthcheck # Scope of https://github.com/orgs/Idea-Pool/projects/4/views/1?pane=issue&itemId=56848307
        run: echo "healthcheck"
      - name: Print deployed URL
        run: |
          URL="https://js-assertion.ideapool.community/"
          echo "Branch main has been successfully deployed: $URL" >> $GITHUB_STEP_SUMMARY
