name: Stack Destroy

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Stack
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Get username of user who triggered the workflow
        id: get-username
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check if user is in CODEOWNERS
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
        run: .github/scripts/codeowners.sh ${{ env.USERNAME }}

      - name: Configure AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CDK_ROLE_ARN }}
          role-session-name: js-assertion-cheat-sheet-stack-destroy
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install CDK dependencies
        working-directory: cdk
        run: npm install

      - name: Destroy Stack
        working-directory: cdk
        run: npm run destroy -- --force

      - name: Remove repository variables
        env:
          GH_TOKEN: ${{ secrets.GH_VARIABLES_TOKEN }}
        run: |
          gh variable delete AWS_BUCKET_NAME --env aws-development
          gh variable delete AWS_DISTRIBUTION_ID --env aws-development
          gh variable delete AWS_WEBSITE_URL --env aws-development
