name: Stack Destroy

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Stack
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CDK_ROLE_ARN }}
          role-session-name: js-assertion-cheat-sheet-stack-destroy
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: cdk
        run: npm install

      - name: Destroy Stack
        working-directory: cdk
        run: npm run destroy -- --force
